# Site Settings and Global Varables
title: PrintF Solutions
email: pliavi.contato@gmail.com
description: > 
  Uma desenvolvedora criada por pessoas diferentes para criação de soluções diferentes.
baseurl: ""
url: "https://printfsolutions.github.io"
github_username: PrintFSolutions

# Build settings
markdown: kramdown